name: PR-Check

on:
  pull_request:
    branches: [ "dev", "main", "prod" ]

jobs:
  Check-pr-uptodate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        with:
          fetch-depth: 0
        uses: actions/checkout@v4
      - run: echo "The repository has been cloned to the runner"
      - run: |
          if git merge-base --is-ancestor ${{github.event.pull_request.base.ref}} HEAD
          then
            echo "Branch is up to date"
          else
            echo "Branch needs update"
            exit 1
          fi
